   public static Integer myValue = 0;
   public static String myString = ''; 
   //Class Member variable
     //Class Member variable
          //Class definition and body
               movedTheNamesToNextLine
   public static Integer getCalculatedValue () {
   if (/^(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$/.test(ip))
  {
   console.log('IP Address verified');
  }
  else
  {
   alert("You have entered an invalid IP address!")
  }
   // Method definition and body
   // do some calculation
   if (true) {
    console.log('sdggg');
    console.log('sdggg');
    console.log('sdggg');
    console.log('sdggg');
  }
      myValue = myValue+10;
      return myValue;
   
   
   // Method definition and body
   // do some calculation
   if () {
    console.log('sdggg');
    console.log('sdggg');
    console.log('sdggg');
    console.log('sdggg');
  }
      myValue = myValue+10;
      return myValue;
   

   // Method definition and body
   // do some calculation
   if () {
    console.log('sdggg');
    console.log('sdggg');
    console.log('sdggg');
    console.log('sdggg');
  }
      myValue = myValue+10;
      return myValue;
   
   
   // Method definition and body
   // do some calculation
   if () {
    console.log('sdggg');
    console.log('sdggg');
    console.log('sdggg');
    console.log('sdggg');
  }
      myValue = myValue+10;
      return myValue;
   
}
